
[loguru_config]
do_configure = true

activation = [["", "true"]]

[[loguru_config.handlers]]
sink = 'ext://sys.stderr'
level = 'INFO'
format = '<green>{time:HH:mm:ss.SSS}</green> | <level>{level: <8}</level> | <level>{message}</level>'

[[loguru_config.handlers]]
sink = './examples/1_configure_loguru_only/logs/file-{time}.log'
level = 'DEBUG'
format = '{time:YYYY-MM-DD HH:mm:ss.SSS} | {level: <8} | {name}:{function}:{line} - {message}'
enqueue = true
serialize = false
