
[loguru_config_std]
# When you want to use multiple loggers, you should set do_configure to false and call configure() on each logger separately.
do_configure = false
activation = [["", "true"]]

[[loguru_config_std.handlers]]
sink = 'ext://sys.stderr'
level = 'INFO'
format = '<green>{time:HH:mm:ss.SSS}</green> | <level>{level: <8}</level> | <level>{message}</level>'

[loguru_config_special]
do_configure = false
activation = [["", "true"]]

[[loguru_config_special.handlers]]
sink = './examples/3_two_loggers/logs/file-{time}.log'
level = 'DEBUG'
format = '{time:YYYY-MM-DD HH:mm:ss.SSS} | {level: <8} | {name}:{function}:{line} - {message}'
enqueue = true
serialize = false
